In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r"C:\Users\test01\Downloads\Churn_Modelling.csv")

In [3]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
dataset.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [6]:
dataset

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
5             645     Spain    Male   44       8  113755.78              2   
6             822    France    Male   50       7       0.00              2   
7             376   Germany  Female   29       4  115046.74              4   
8             501    France    Male   44       4  142051.07              2   
9             684    France    Male   27       2  134603.88              1   
10            528    France    Male   31       6  102016.72              2   
11            497     Spain    Male   24       3       0.00              2   
12            476    France  Female   34      10       0.00              2   
13            549    France  Female   25       5       0.00              2   
14            635     Spain  Female   35       7       0.00              2   
15            616   Germany    Male   45       3  143129.41              2   
16            653   Germany    Male   58       1  132602.88              1   
17            549     Spain  Female   24       9       0.00              2   
18            587     Spain    Male   45       6       0.00              1   
19            726    France  Female   24       6       0.00              2   
20            732    France    Male   41       8       0.00              2   
21            636     Spain  Female   32       8       0.00              2   
22            510     Spain  Female   38       4       0.00              1   
23            669    France    Male   46       3       0.00              2   
24            846    France  Female   38       5       0.00              1   
25            577    France    Male   25       3       0.00              2   
26            756   Germany    Male   36       2  136815.64              1   
27            571    France    Male   44       9       0.00              2   
28            574   Germany  Female   43       3  141349.43              1   
29            411    France    Male   29       0   59697.17              2   
...           ...       ...     ...  ...     ...        ...            ...   
9970          518    France    Male   42       7  151027.05              2   
9971          833    France  Female   34       3  144751.81              1   
9972          758    France    Male   26       4  155739.76              1   
9973          611    France    Male   27       7       0.00              2   
9974          583    France    Male   33       7  122531.86              1   
9975          610   Germany    Male   50       1  113957.01              2   
9976          637    France  Female   33       7  103377.81              1   
9977          683    France  Female   32       9       0.00              2   
9978          774    France    Male   40       9   93017.47              2   
9979          677    France  Female   58       1   90022.85              1   
9980          741     Spain    Male   35       6   74371.49              1   
9981          498   Germany    Male   42       3  152039.70              1   
9982          655   Germany  Female   46       7  137145.12              1   
9983          613    France    Male   40       4       0.00              1   
9984          602   Germany    Male   35       7   90602.42              2   
9985          659    France    Male   36       6  123841.49              2   
9986          673   Germany    Male   47       1  183579.54              2   
9987          606     Spain    Male   30       8  180307.73              2   
9988          775    France    Male   30       4       0.00              2   
9989          841     Spain 

In [7]:
x=dataset.iloc[:,:-1].values

In [8]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y=dataset.iloc[:,-1].values

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lb=LabelEncoder()

In [13]:
x[:,1]=lb.fit_transform(x[:,1])

In [14]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
x[:,2]=lb.fit_transform(x[:,2])

In [16]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
one=OneHotEncoder(categorical_features=[1])

In [19]:
x=one.fit_transform(x).toarray()

In [20]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [21]:
x=x[:,1:]

In [22]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [25]:
x_train

array([[0.0000000e+00, 1.0000000e+00, 6.6700000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [1.0000000e+00, 0.0000000e+00, 4.2700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [0.0000000e+00, 0.0000000e+00, 5.3500000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.3800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 5.9000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 6.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [26]:
x_test

array([[1.0000000e+00, 0.0000000e+00, 5.9700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.9285267e+05],
       [0.0000000e+00, 0.0000000e+00, 5.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.2870210e+05],
       [0.0000000e+00, 1.0000000e+00, 7.0600000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 7.5732250e+04],
       ...,
       [0.0000000e+00, 1.0000000e+00, 5.7800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.4153319e+05],
       [1.0000000e+00, 0.0000000e+00, 6.5000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.1276480e+04],
       [1.0000000e+00, 0.0000000e+00, 5.7300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.9295060e+05]])

In [27]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [28]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
from sklearn.preprocessing import MinMaxScaler#since we using gradient descent

In [30]:
sc=MinMaxScaler()

In [31]:
x_train=sc.fit_transform(x_train)

In [32]:
x_test=sc.transform(x_test)

In [33]:
x_train

array([[0.        , 1.        , 0.634     , ..., 1.        , 0.        ,
        0.81917353],
       [1.        , 0.        , 0.154     , ..., 1.        , 1.        ,
        0.28545936],
       [0.        , 0.        , 0.37      , ..., 1.        , 0.        ,
        0.92818454],
       ...,
       [0.        , 0.        , 0.776     , ..., 1.        , 0.        ,
        0.90717809],
       [0.        , 1.        , 0.48      , ..., 1.        , 1.        ,
        0.74376393],
       [1.        , 0.        , 0.546     , ..., 1.        , 0.        ,
        0.59427515]])

In [34]:
x_test

array([[1.        , 0.        , 0.494     , ..., 1.        , 1.        ,
        0.96429754],
       [0.        , 0.        , 0.346     , ..., 1.        , 0.        ,
        0.64351406],
       [0.        , 1.        , 0.712     , ..., 1.        , 1.        ,
        0.37863951],
       ...,
       [0.        , 1.        , 0.456     , ..., 1.        , 0.        ,
        0.70767563],
       [1.        , 0.        , 0.6       , ..., 1.        , 1.        ,
        0.05632988],
       [1.        , 0.        , 0.446     , ..., 1.        , 0.        ,
        0.96478724]])

In [35]:
!pip install tensorflow==1.5

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [36]:
import tensorflow

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [37]:
import keras

Using TensorFlow backend.


# Neural Network Model

# Step 1: Importing Libaries

In [38]:
from keras.models import Sequential#to initialize
from keras.layers import Dense#to add layers

# Step 2: Initialize the neural network model

In [39]:
model=Sequential()
x_train.shape

(8000, 11)

# step 3: Add input layer

In [40]:
model.add(Dense(input_dim=11,init="random_uniform",activation="relu",output_dim=20))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=20, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


# step 4: Add hidden layer

In [41]:
model.add(Dense(init="random_uniform",activation="relu",output_dim=15))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=15, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


# step 5: Add output layer

In [42]:
model.add(Dense(init="random_uniform",activation="sigmoid",output_dim=1))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [43]:
#11 neuron in i/p layer
#6 neuron in hidden layer
#1 neuron in output layer

# step 6: Compile the NN model

In [44]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])#loss='mse' for regression model

# step 7: Train the model

In [45]:
model.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.5414 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 0s 25us/step - loss: 0.4716 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4570 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4480 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4424 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4372 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4321 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4289 - acc: 0.8105
Epoch 9/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4258 - acc: 0.8166
Epoch 10/100
8000/8000 [==============================] - 0s 24us/step - loss: 0.4238 - acc: 0.8204
Epoch 11

8000/8000 [==============================] - 0s 27us/step - loss: 0.4019 - acc: 0.8345
Epoch 84/100
8000/8000 [==============================] - 0s 26us/step - loss: 0.4018 - acc: 0.8354
Epoch 85/100
8000/8000 [==============================] - 0s 26us/step - loss: 0.4019 - acc: 0.8342
Epoch 86/100
8000/8000 [==============================] - 0s 26us/step - loss: 0.4028 - acc: 0.8348
Epoch 87/100
8000/8000 [==============================] - 0s 25us/step - loss: 0.4026 - acc: 0.8357
Epoch 88/100
8000/8000 [==============================] - 0s 26us/step - loss: 0.4031 - acc: 0.8349
Epoch 89/100
8000/8000 [==============================] - 0s 25us/step - loss: 0.4027 - acc: 0.8341
Epoch 90/100
8000/8000 [==============================] - 0s 27us/step - loss: 0.4017 - acc: 0.8349
Epoch 91/100
8000/8000 [==============================] - 0s 25us/step - loss: 0.4014 - acc: 0.8335
Epoch 92/100
8000/8000 [==============================] - 0s 29us/step - loss: 0.4014 - acc: 0.8348
Epoch 93/100


# step 8: Test the model

In [46]:
y_pred=model.predict(x_test)

In [47]:
y_pred#beacuse we used sigmoid function

array([[0.20104253],
       [0.3398843 ],
       [0.14228445],
       ...,
       [0.17075782],
       [0.1346818 ],
       [0.12985632]], dtype=float32)

In [48]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [49]:
y_pred=y_pred>0.5

In [50]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
accuracy_score(y_test,y_pred)

0.841