In [5]:
import numpy as np

In [3]:
#array()
arr=np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [6]:
arr.size

4

In [7]:
arr.shape

(4,)

In [8]:
arr2=np.array([[1,2,3,4],[33,44,22,11],[55,23,22,10]])

In [9]:
arr2.ndim

2

In [10]:
arr2.size

12

In [11]:
arr2.shape

(3, 4)

In [13]:
arr2=np.array([[1,2,3,4],[2,4,8,1],[1,2,3,4],[2,4,8,1]])

In [14]:
arr2

array([[1, 2, 3, 4],
       [2, 4, 8, 1],
       [1, 2, 3, 4],
       [2, 4, 8, 1]])

In [15]:
arr3=np.array([[1,2,3],[2,4,8,1],[1,2,3,4],[2,4,8,1]])

In [16]:
arr3

array([list([1, 2, 3]), list([2, 4, 8, 1]), list([1, 2, 3, 4]),
       list([2, 4, 8, 1])], dtype=object)

In [21]:
arr4=np.array([[[1,2,3,4],[3,1,2,5]],[[1,2,3,4],[3,1,2,5]],[[1,2,3,4],[3,1,2,5]]],float)

In [22]:
arr4

array([[[1., 2., 3., 4.],
        [3., 1., 2., 5.]],

       [[1., 2., 3., 4.],
        [3., 1., 2., 5.]],

       [[1., 2., 3., 4.],
        [3., 1., 2., 5.]]])

In [19]:
arr4.shape

(3, 2, 4)

In [20]:
arr4.size

24

In [23]:
arr4.dtype

dtype('float64')

In [24]:
arr4.itemsize

8

In [25]:
arr4[0]

array([[1., 2., 3., 4.],
       [3., 1., 2., 5.]])

In [26]:
print(arr4[0])

[[1. 2. 3. 4.]
 [3. 1. 2. 5.]]


In [27]:
arr4=np.array([[[1,2,3,4],[3,1,2,5]],[[11,22,33,44],[31,11,21,51]],[[91,92,93,94],[93,91,92,95]]],float)

In [28]:
arr4[1][0][3]

44.0

In [30]:
arr4[0:3,0:1]

array([[[ 1.,  2.,  3.,  4.]],

       [[11., 22., 33., 44.]],

       [[91., 92., 93., 94.]]])

In [33]:
arr4[1].size

8

In [32]:
arr4

array([[[ 1.,  2.,  3.,  4.],
        [ 3.,  1.,  2.,  5.]],

       [[11., 22., 33., 44.],
        [31., 11., 21., 51.]],

       [[91., 92., 93., 94.],
        [93., 91., 92., 95.]]])

In [34]:
arr5=arr4.flatten()

In [35]:
arr5

array([ 1.,  2.,  3.,  4.,  3.,  1.,  2.,  5., 11., 22., 33., 44., 31.,
       11., 21., 51., 91., 92., 93., 94., 93., 91., 92., 95.])

In [36]:
arr6=arr5.reshape(3,2,4)

In [37]:
arr6

array([[[ 1.,  2.,  3.,  4.],
        [ 3.,  1.,  2.,  5.]],

       [[11., 22., 33., 44.],
        [31., 11., 21., 51.]],

       [[91., 92., 93., 94.],
        [93., 91., 92., 95.]]])

In [ ]:
#arange()

In [41]:
arr1

NameError: name 'arr1' is not defined

In [8]:
#arange()
arra=np.arange(0,10)

In [9]:
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#linspacenp.linspace(0,10)

In [11]:
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arra.min()

0

In [13]:
arra.max()

9

# 

# logspace()

In [20]:
a1=np.logspace(1,2,2,base=10)

In [21]:
a1

array([ 10., 100.])

# zeros()

In [28]:
z1=np.zeros([2,2],dtype=int)

In [29]:
z1

array([[0, 0],
       [0, 0]])

# ones()

In [30]:
z2=np.ones([2,2],dtype=int)

In [31]:
z2

array([[1, 1],
       [1, 1]])